START TRANSACTION;
CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) CHARACTER SET utf8
);

CREATE TABLE IF NOT EXISTS todos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(31) NOT NULL CHARACTER SET utf8,
    body VARCHAR(255) NOT NULL CHARACTER SET utf8,
    done BOOLEAN NOT NULL DEFAULT false,
    user_id INT UNSIGNED NOT NULL,

    FOREIGN KEY todo_user (user_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
COMMIT;
